# Pipeline jobs
stages:
  - first_job
  - second_job

first:
  stage: first_job
  script:
    - echo "Mon premier job"
  tags:
    - cli

second:
  stage: first_job
  script:
    - echo "Mon second job"
  tags:
    - cli

third:
  stage: second_job
  script:
    - echo "Mon job final"
  tags:
    - conteneur
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
