version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.hadrien.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.hadrien.com'
        registry_external_url 'https://gitlab.hadrien.com:5000'
    ports:
      - '8080:80'
      - '8443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab

  gitlab-runner-shell:
    image: gitlab/gitlab-runner
    restart: always
    container_name: shell-runner
    depends_on:
      - gitlab
    volumes:
      - '${GITLAB_HOME}/config/gitlab-runner-shell:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - gitlab

networks:
 gitlab:
