services:
  gitlab-runner-shell:
    image: gitlab/gitlab-runner
    restart: always
    container_name: shell-runner
    volumes:
      - '${GITLAB_HOME}/config/gitlab-runner-shell:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

  gitlab-runner-docker:
    image: gitlab/gitlab-runner
    restart: always
    container_name: docker-runner
    volumes:
      - '${GITLAB_HOME}/config/gitlab-runner-docker:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
 gitlab:
